name: Crawl and extract text
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: raw-text-chunks
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
