name: Crawl and extract text
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: raw-text-chunks
    required: true
  - name: textchunksize
    inputType: FreeText
    description: 200
    defaultValue: 1000
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
