name: Create embeddings
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw-text-chunks-test-01-04
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: embeddings-sbert-all-MiniLM-L6-v2
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
